/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5;

/**
 *
 * @author gaby
 */
public class APP1 extends javax.swing.JFrame {

    /**
     * Creates new form APP1
     */
    public APP1() {
        initComponents();
        this.setSize(488,680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jrbarea = new javax.swing.JRadioButton();
        jrbcircunferencia = new javax.swing.JRadioButton();
        jrbVolumenEsfera = new javax.swing.JRadioButton();
        jrbVolumenCubo = new javax.swing.JRadioButton();
        jrbPromedio = new javax.swing.JRadioButton();
        jtxtlado1 = new javax.swing.JTextField();
        jtxtlado2 = new javax.swing.JTextField();
        txtMedida = new javax.swing.JTextField();
        jtxtdiagonal = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblDiagonal = new javax.swing.JLabel();
        rbRadio = new javax.swing.JRadioButton();
        rbDiametro = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblCircunferencia = new javax.swing.JLabel();
        rbRadioV = new javax.swing.JRadioButton();
        jrbDiametroV = new javax.swing.JRadioButton();
        txtMedidaV = new javax.swing.JTextField();
        lblVolumenEsfera = new javax.swing.JLabel();
        lblVolumenCubo = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        lblPromedio = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtP2 = new javax.swing.JTextField();
        txtP3 = new javax.swing.JTextField();
        txtP4 = new javax.swing.JTextField();
        txtP5 = new javax.swing.JTextField();
        txtP6 = new javax.swing.JTextField();
        txtP7 = new javax.swing.JTextField();
        txtP8 = new javax.swing.JTextField();
        txtP9 = new javax.swing.JTextField();
        txtP10 = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el calculo que desea realizar:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 20, 268, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lado 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(88, 83, 60, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lado 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(88, 121, 50, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Diagonal");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(102, 471, 60, 14);

        jrbarea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbarea.setText("Area y Diagonal de fig. de 4 lados");
        jrbarea.setContentAreaFilled(false);
        jrbarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbareaActionPerformed(evt);
            }
        });
        getContentPane().add(jrbarea);
        jrbarea.setBounds(65, 55, 260, 23);

        jrbcircunferencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbcircunferencia.setText("Circunferencia de un circulo");
        jrbcircunferencia.setContentAreaFilled(false);
        jrbcircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbcircunferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jrbcircunferencia);
        jrbcircunferencia.setBounds(65, 156, 230, 23);

        jrbVolumenEsfera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbVolumenEsfera.setText("Volumen de una esfera");
        jrbVolumenEsfera.setContentAreaFilled(false);
        jrbVolumenEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVolumenEsferaActionPerformed(evt);
            }
        });
        getContentPane().add(jrbVolumenEsfera);
        jrbVolumenEsfera.setBounds(61, 288, 210, 23);

        jrbVolumenCubo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbVolumenCubo.setText("Volumen de un cubo");
        jrbVolumenCubo.setContentAreaFilled(false);
        jrbVolumenCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVolumenCuboActionPerformed(evt);
            }
        });
        getContentPane().add(jrbVolumenCubo);
        jrbVolumenCubo.setBounds(61, 427, 190, 23);

        jrbPromedio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbPromedio.setText("Promedio (10 num)");
        jrbPromedio.setContentAreaFilled(false);
        jrbPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(jrbPromedio);
        jrbPromedio.setBounds(61, 513, 190, 23);

        jtxtlado1.setEnabled(false);
        getContentPane().add(jtxtlado1);
        jtxtlado1.setBounds(188, 80, 84, 20);

        jtxtlado2.setEnabled(false);
        getContentPane().add(jtxtlado2);
        jtxtlado2.setBounds(188, 118, 84, 20);

        txtMedida.setEnabled(false);
        getContentPane().add(txtMedida);
        txtMedida.setBounds(188, 225, 84, 20);

        jtxtdiagonal.setEnabled(false);
        getContentPane().add(jtxtdiagonal);
        jtxtdiagonal.setBounds(188, 468, 84, 20);

        lblArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblArea);
        lblArea.setBounds(297, 83, 100, 0);

        lblDiagonal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblDiagonal);
        lblDiagonal.setBounds(297, 121, 100, 0);

        rbRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbRadio.setForeground(new java.awt.Color(255, 255, 255));
        rbRadio.setText("Radio");
        rbRadio.setContentAreaFilled(false);
        rbRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRadioActionPerformed(evt);
            }
        });
        getContentPane().add(rbRadio);
        rbRadio.setBounds(91, 197, 130, 23);

        rbDiametro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbDiametro.setForeground(new java.awt.Color(255, 255, 255));
        rbDiametro.setText("Diametro");
        rbDiametro.setContentAreaFilled(false);
        rbDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiametroActionPerformed(evt);
            }
        });
        getContentPane().add(rbDiametro);
        rbDiametro.setBounds(83, 247, 140, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 630, 77, 23);

        lblCircunferencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblCircunferencia);
        lblCircunferencia.setBounds(297, 231, 100, 0);

        rbRadioV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbRadioV.setForeground(new java.awt.Color(255, 255, 255));
        rbRadioV.setText("Radio");
        rbRadioV.setContentAreaFilled(false);
        rbRadioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRadioVActionPerformed(evt);
            }
        });
        getContentPane().add(rbRadioV);
        rbRadioV.setBounds(87, 329, 130, 23);

        jrbDiametroV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbDiametroV.setForeground(new java.awt.Color(255, 255, 255));
        jrbDiametroV.setText("Diametro");
        jrbDiametroV.setContentAreaFilled(false);
        jrbDiametroV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDiametroVActionPerformed(evt);
            }
        });
        getContentPane().add(jrbDiametroV);
        jrbDiametroV.setBounds(87, 376, 140, 23);

        txtMedidaV.setEnabled(false);
        txtMedidaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedidaVActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedidaV);
        txtMedidaV.setBounds(188, 354, 84, 20);

        lblVolumenEsfera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblVolumenEsfera);
        lblVolumenEsfera.setBounds(297, 357, 100, 0);

        lblVolumenCubo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblVolumenCubo);
        lblVolumenCubo.setBounds(297, 471, 100, 0);

        txtP1.setEnabled(false);
        txtP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtP1);
        txtP1.setBounds(61, 543, 32, 23);

        lblPromedio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblPromedio);
        lblPromedio.setBounds(297, 554, 180, 26);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 630, 64, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Volver a menu principal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 630, 170, 23);

        txtP2.setEnabled(false);
        getContentPane().add(txtP2);
        txtP2.setBounds(103, 544, 35, 20);

        txtP3.setEnabled(false);
        getContentPane().add(txtP3);
        txtP3.setBounds(144, 544, 38, 20);

        txtP4.setEnabled(false);
        getContentPane().add(txtP4);
        txtP4.setBounds(188, 544, 36, 20);

        txtP5.setEnabled(false);
        getContentPane().add(txtP5);
        txtP5.setBounds(230, 544, 37, 20);

        txtP6.setEnabled(false);
        getContentPane().add(txtP6);
        txtP6.setBounds(61, 584, 32, 20);

        txtP7.setEnabled(false);
        getContentPane().add(txtP7);
        txtP7.setBounds(103, 584, 35, 20);

        txtP8.setEnabled(false);
        getContentPane().add(txtP8);
        txtP8.setBounds(144, 584, 38, 20);

        txtP9.setEnabled(false);
        getContentPane().add(txtP9);
        txtP9.setBounds(188, 584, 40, 20);

        txtP10.setEnabled(false);
        getContentPane().add(txtP10);
        txtP10.setBounds(234, 584, 37, 20);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        btnBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBorrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnBorrar);
        btnBorrar.setBounds(140, 630, 69, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\manuel\\Desktop\\Gabriela Cortez\\UES\\Programacion 2\\GUIA2\\GUIA5\\build\\classes\\imagenes\\b2aad9a1f7669d867d312fa875c459f8.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 530, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbareaActionPerformed
        if(jrbarea.isSelected()){
            jtxtlado1.setEnabled(true);
            jtxtlado2.setEnabled(true);
            jrbcircunferencia.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            rbRadioV.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbPromedio.setSelected(false);
        }
    }//GEN-LAST:event_jrbareaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jrbarea.isSelected()){
            int lado1, lado2, area;
        double diagonal;
        lado1=Integer.parseInt(jtxtlado1.getText());
        lado2=Integer.parseInt(jtxtlado2.getText());
        area=lado1*lado2;
        diagonal=Math.sqrt(Math.pow(lado1,2)+Math.pow(lado2,2));
        lblArea.setText("Area: "+area);
        lblDiagonal.setText("Diagonal: "+diagonal);
        
        }if(jrbcircunferencia.isSelected()){
            if(rbDiametro.isSelected()){
            double diametro, perimetro;
            diametro=Double.parseDouble(txtMedida.getText());
            perimetro=(3.1416*diametro);
            lblCircunferencia.setText("Perimetro:"+perimetro);
            }else if(rbRadio.isSelected()){
            double radio, perimetro;
            radio=Double.parseDouble(txtMedida.getText());
            perimetro=(3.1416*radio*2);
            lblCircunferencia.setText("Perimetro:"+perimetro);
        }
        }if(jrbVolumenEsfera.isSelected()){
            if(rbRadioV.isSelected()){
            double radio, volumen;
            radio=Double.parseDouble(txtMedidaV.getText());
            volumen =((4*(3.1416)*(Math.pow(radio, 3)))/3);
            lblVolumenEsfera.setText("Volumen: "+volumen);
            }else if(jrbDiametroV.isSelected()){
            double diametro, radio, volumen;
            diametro=Double.parseDouble(txtMedida.getText());
            radio=diametro/2;
            volumen =((4*3.1416*(Math.pow(radio, 3)))/3);
            lblVolumenEsfera.setText("Volumen: " +volumen);
        }
        }if(jrbVolumenCubo.isSelected()){
            double diagonal, volumen, lado;
            diagonal=Double.parseDouble(jtxtdiagonal.getText());
             lado=diagonal/(Math.sqrt(2));
            volumen=Math.pow(lado, 3);
            lblVolumenCubo.setText("Volumen: "+volumen);
        }if(jrbPromedio.isSelected()){
            double n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, promedio;
            n1=Double.parseDouble(txtP1.getText());
            n2=Double.parseDouble(txtP2.getText());
            n3=Double.parseDouble(txtP3.getText());
            n4=Double.parseDouble(txtP4.getText());
            n5=Double.parseDouble(txtP5.getText());
            n6=Double.parseDouble(txtP6.getText());
            n7=Double.parseDouble(txtP7.getText());
            n8=Double.parseDouble(txtP8.getText());
            n9=Double.parseDouble(txtP9.getText());
            n10=Double.parseDouble(txtP10.getText());
            
            promedio=((n1+n2+n3+n4+n5+n6+n7+n8+n9+n10)/10);
            lblPromedio.setText("Promedio:"+ promedio);
             
                    
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrbcircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbcircunferenciaActionPerformed
        
        if(jrbcircunferencia.isSelected()){
            
            txtMedida.setEnabled(true);
            txtMedidaV.setEnabled(false);
            txtP1.setEnabled(false);
            txtP10.setEnabled(false);
            txtP2.setEnabled(false);
            txtP3.setEnabled(false);
            txtP4.setEnabled(false);
            txtP5.setEnabled(false);
            txtP6.setEnabled(false);
            txtP7.setEnabled(false);
            txtP8.setEnabled(false);
            txtP9.setEnabled(false);
            jtxtdiagonal.setEnabled(false);
            jtxtlado1.setEnabled(false);
            jtxtlado2.setEnabled(false);
            
            
            jrbarea.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbRadioV.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbPromedio.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(true);
            if(rbDiametro.isSelected()){
                rbRadio.setSelected(false);
            }
            }
    }//GEN-LAST:event_jrbcircunferenciaActionPerformed

    private void jrbVolumenEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVolumenEsferaActionPerformed
        if(jrbVolumenEsfera.isSelected()){
            
            txtMedida.setEnabled(false);
            txtMedidaV.setEnabled(true);
            txtP1.setEnabled(false);
            txtP10.setEnabled(false);
            txtP2.setEnabled(false);
            txtP3.setEnabled(false);
            txtP4.setEnabled(false);
            txtP5.setEnabled(false);
            txtP6.setEnabled(false);
            txtP7.setEnabled(false);
            txtP8.setEnabled(false);
            txtP9.setEnabled(false);
            jtxtdiagonal.setEnabled(false);
            jtxtlado1.setEnabled(false);
            jtxtlado2.setEnabled(false);
            
            jrbarea.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbcircunferencia.setSelected(false);
            rbRadioV.setSelected(true);
           if(jrbDiametroV.isSelected()){
                rbRadio.setSelected(false);
            }
        }
    }//GEN-LAST:event_jrbVolumenEsferaActionPerformed

    private void rbRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRadioActionPerformed
        if(rbRadio.isSelected()){
            jrbcircunferencia.setSelected(true);
            rbDiametro.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbarea.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbRadioV.setSelected(false);
        }
    }//GEN-LAST:event_rbRadioActionPerformed
    
    private void rbDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiametroActionPerformed
        if(rbDiametro.isSelected()){
            jrbcircunferencia.setSelected(true);
            rbRadio.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbarea.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbRadioV.setSelected(false);
        }
    }//GEN-LAST:event_rbDiametroActionPerformed

    private void rbRadioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRadioVActionPerformed
        if(rbRadioV.isSelected()){
            jrbVolumenEsfera.setSelected(true);
            jrbDiametroV.setSelected(false);
            jrbarea.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbcircunferencia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRadioVActionPerformed

    private void jrbDiametroVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDiametroVActionPerformed
        if(jrbDiametroV.isSelected()){
            jrbVolumenEsfera.setSelected(true);
            rbRadioV.setSelected(false);
            jrbarea.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbcircunferencia.setSelected(false);
        }
    }//GEN-LAST:event_jrbDiametroVActionPerformed

    private void jrbVolumenCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVolumenCuboActionPerformed
        if(jrbVolumenCubo.isSelected()){
            
            txtMedida.setEnabled(false);
            txtMedidaV.setEnabled(false);
            txtP1.setEnabled(false);
            txtP10.setEnabled(false);
            txtP2.setEnabled(false);
            txtP3.setEnabled(false);
            txtP4.setEnabled(false);
            txtP5.setEnabled(false);
            txtP6.setEnabled(false);
            txtP7.setEnabled(false);
            txtP8.setEnabled(false);
            txtP9.setEnabled(false);
            jtxtdiagonal.setEnabled(true);
            jtxtlado1.setEnabled(false);
            jtxtlado2.setEnabled(false);
            
            jrbcircunferencia.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            rbRadioV.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbPromedio.setSelected(false);
            jrbarea.setSelected(false);
        }
    }//GEN-LAST:event_jrbVolumenCuboActionPerformed
    
    private void jrbPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPromedioActionPerformed
        if(jrbPromedio.isSelected()){
            
            txtMedida.setEnabled(false);
            txtMedidaV.setEnabled(false);
            txtP1.setEnabled(true);
            txtP10.setEnabled(true);
            txtP2.setEnabled(true);
            txtP3.setEnabled(true);
            txtP4.setEnabled(true);
            txtP5.setEnabled(true);
            txtP6.setEnabled(true);
            txtP7.setEnabled(true);
            txtP8.setEnabled(true);
            txtP9.setEnabled(true);
            jtxtdiagonal.setEnabled(false);
            jtxtlado1.setEnabled(false);
            jtxtlado2.setEnabled(false);
            
            jrbcircunferencia.setSelected(false);
            jrbDiametroV.setSelected(false);
            rbDiametro.setSelected(false);
            rbRadio.setSelected(false);
            rbRadioV.setSelected(false);
            jrbVolumenEsfera.setSelected(false);
            jrbVolumenCubo.setSelected(false);
            jrbarea.setSelected(false);
            
            
            
            
        }
    }//GEN-LAST:event_jrbPromedioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Menu ventana = new Menu();
            this.setVisible(false);
            ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBorrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBorrarKeyPressed
        
    }//GEN-LAST:event_btnBorrarKeyPressed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtMedida.setText("");
        txtMedidaV.setText("");
        txtP1.setText("");
        txtP10.setText("");
        txtP2.setText("");
        txtP3.setText("");
        txtP4.setText("");
        txtP5.setText("");
        txtP6.setText("");
        txtP7.setText("");
        txtP8.setText("");
        txtP9.setText("");
        lblPromedio.setText("");
        jtxtdiagonal.setText("");
        jtxtlado1.setText("");
        jtxtlado2.setText("");
        lblArea.setText("");
        lblCircunferencia.setText("");
        lblDiagonal.setText("");
        lblVolumenCubo.setText("");
        lblVolumenEsfera.setText("");
        jrbDiametroV.setSelected(false);
        jrbPromedio.setSelected(false);
        jrbVolumenCubo.setSelected(false);
        jrbVolumenEsfera.setSelected(false);
        jrbarea.setSelected(false);
        jrbcircunferencia.setSelected(false);
        rbDiametro.setSelected(false);
        rbRadio.setSelected(false);
        rbRadioV.setSelected(false);
        //Desabilita todos los textfield
        txtMedida.setEnabled(false);
        txtMedidaV.setEnabled(false);
        txtP1.setEnabled(false);
        txtP10.setEnabled(false);
        txtP2.setEnabled(false);
        txtP3.setEnabled(false);
        txtP4.setEnabled(false);
        txtP5.setEnabled(false);
        txtP6.setEnabled(false);
        txtP7.setEnabled(false);
        txtP8.setEnabled(false);
        txtP9.setEnabled(false);
        jtxtdiagonal.setEnabled(false);
        jtxtlado1.setEnabled(false);
        jtxtlado2.setEnabled(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1ActionPerformed

    private void txtMedidaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedidaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedidaVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jrbDiametroV;
    private javax.swing.JRadioButton jrbPromedio;
    private javax.swing.JRadioButton jrbVolumenCubo;
    private javax.swing.JRadioButton jrbVolumenEsfera;
    private javax.swing.JRadioButton jrbarea;
    private javax.swing.JRadioButton jrbcircunferencia;
    private javax.swing.JTextField jtxtdiagonal;
    private javax.swing.JTextField jtxtlado1;
    private javax.swing.JTextField jtxtlado2;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCircunferencia;
    private javax.swing.JLabel lblDiagonal;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblVolumenCubo;
    private javax.swing.JLabel lblVolumenEsfera;
    private javax.swing.JRadioButton rbDiametro;
    private javax.swing.JRadioButton rbRadio;
    private javax.swing.JRadioButton rbRadioV;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextField txtMedidaV;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP10;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    private javax.swing.JTextField txtP4;
    private javax.swing.JTextField txtP5;
    private javax.swing.JTextField txtP6;
    private javax.swing.JTextField txtP7;
    private javax.swing.JTextField txtP8;
    private javax.swing.JTextField txtP9;
    // End of variables declaration//GEN-END:variables
}
